### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by casey** [P3KI/bendy#36]
Would it be possible to push a new release of bendy on crates.io?

I'm preparing to release a crate that depends on serde support. Currently I'm depending on bendy via github, but released crates may only have crates.io dependencies.

**Comment by thequux** [comment]
Absolutely; would Monday work for you, or would you prefer that i get it
done tonight?

**Comment by casey** [comment]
No rush at all! I'm probably going to finish the release in a week, at the absolute earliest. Thank you for being so responsive though  ^_^

**Comment by thequux** [comment]
0.3.0 has been released! Sorry it took an extra couple of days; I've been really squeezed by other work tasks this week.

**Comment by casey** [comment]
No worries at all, thank you very much!
