### ISSUE TITLE
Switch to another error handling library

### ISSUE THREAD

**Issue by scrabsha** [P3KI/bendy#40]
Hello,
I discovered `bendy` a few days ago, and noticed that it uses `failure` for error handling. Unfortunately, since [commit 
135e2a3](https://github.com/rust-lang-nursery/failure/commit/135e2a3b9af422d9a9dc37ce7c69354c9b36e94b), failure is deprecated. The notice says that users may like to use either `anyhow` or `thiserror`.

Is there any plan in switching to another error handling library?

**Comment by 0ndorio** [comment]
Hi @scileo , AFAIK its planned to switch soon. :)

**Comment by 0ndorio** [comment]
I spent some time to check the current landscape of error handling crates. And we are still a bit puzzled which crate or combination of crates will work out as a replacement for failure. Especially as we want bendy to stay `no_std` compatible.

As far as I can say `failure` actually provides two different features and both are used in the code base:

   1. A generic error wrapper, which allows to pass or wrap different kind of
       errors between functions.

   2. An error derive macro, which removes all of the boilerplate necessary to
       come up with a new error type.

As failure has been marked as deprecated it seems like we currently have the following candidates for a replacement:

   - `anyhow` -   support for feature 1
   - `snafu` - support for feature 2
   - `err-derive` - support for feature 2

Other crates not considered as it seems like they don't support `no_std`:

   - `thiserror` - feature 2
   - `error-chain` - feature 1 & 2

---

The `no_std` support for the error type deriving crates above is provided as follows:

   -  `snafu` has a custom `Error` trait which is used in `no_std` environments,
      which AFAIK is not exposed for manual implementations but only through
      their derive macro

   - `err-derive` will just skip the derive call for `Error` and only implement
     `Display` and `From` in `no_std` environments

---

Right now I would tend to go with a combination of `anyhow` and `snafu` but I am still a bit unsure about this decision. Any additional input would be great.

**Comment by scileo** [comment]
I am not an expert in error handling. I just opened this issue because I was using bendy for a project, and saw that it uses a now-deprecated dependency.

It seems to me that the usage of `anyhow` for a library is a bit counter-intuitive since it is harder to deal with errors generated by such crate (I mean, `match`ing over an enum is way simpler than several calls to `downcast_*`). As such, it may be harder for crates using `bendy` to recover from errors.

Again, I don't know how the code base is structured, and I don't have that experience in error handling. So this may be completely off-topic.

**Comment by 0ndorio** [comment]
> I am not an expert in error handling. I just opened this issue because I was using bendy for a project, and saw that it uses a now-deprecated dependency.
> 
> It seems to me that the usage of `anyhow` for a library is a bit counter-intuitive since it is harder to deal with errors generated by such crate (I mean, `match`ing over an enum is way simpler than several calls to `downcast_*`). As such, it may be harder for crates using `bendy` to recover from errors.
> 
> Again, I don't know how the code base is structured, and I don't have that experience in error handling. So this may be completely off-topic.

I wouldn't propose to use `anyhow` as a replacement for any of the already existing error types but only to replace the `failure` based generic error handling mechanism we already use internally (e.g. to store the origin of the `MalformedContent` error variant.

**Comment by casey** [comment]
I just wanted to jump in and say that I've used Snafu extensively, and it's been great.

I'm using snafu in Intermodal, a bittorrent metainfo utility that uses bendy for bencode encoding and decoding. The [error enum](https://github.com/casey/intermodal/blob/master/src/error.rs) is pretty large, and probably a good example of Snafu being used.

If you search for ["context"](https://github.com/casey/intermodal/search?q=context), you can see how snafu context constructors work to create higher level errors from lower level errors.
